apiVersion: k8s.restorehub.co/v1beta2
kind: Repository
metadata:
  name: {{ .Values.repoName }}-repository-restorehub
spec:
  sshPath: {{ .Values.sshPath }}
  repoName: {{ .Values.repoName }}
  sshKey: {{ .Values.sshKey }}